import { StyleSheet, Dimensions } from 'react-native';

export const getStyles = (theme: any) => {
  const { colors: COLORS, spacing: SPACING, radius: RADIUS, fontSizes: FONT_SIZES, glass: GLASS } = theme;
  const { width } = Dimensions.get('window');

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: COLORS.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: SPACING.m,
      paddingTop: SPACING.xl,
      paddingBottom: SPACING.m,
      backgroundColor: COLORS.surface,
      ...GLASS?.card,
    },
    backButton: {
      padding: SPACING.s,
    },
    headerTitle: {
      flex: 1,
      fontSize: FONT_SIZES.l,
      fontWeight: '700',
      color: COLORS.text,
      textAlign: 'center',
      marginRight: 40,
    },
    scrollContent: {
      paddingBottom: 40,
    },
    projectCard: {
      marginHorizontal: SPACING.m,
      padding: SPACING.l,
      backgroundColor: COLORS.surface,
      borderRadius: RADIUS.l,
      borderWidth: 1,
      borderColor: COLORS.border,
      marginBottom: SPACING.l,
      marginTop: SPACING.m,
      ...GLASS?.card,
    },
    projectNameRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.s,
    },
    projectName: {
      fontSize: FONT_SIZES.xl,
      fontWeight: '800',
      color: COLORS.text,
      flex: 1,
    },
    cardHeaderActions: {
      flexDirection: 'row',
      gap: SPACING.s,
    },
    cardActionBtn: {
      padding: SPACING.s,
      borderRadius: RADIUS.s,
      backgroundColor: COLORS.surfaceHighlight,
    },
    cardDeleteBtn: {
      backgroundColor: COLORS.error + '10',
    },
    clientRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: SPACING.s,
    },
    clientName: {
      fontSize: FONT_SIZES.m,
      color: COLORS.textMuted,
    },
    addressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: SPACING.m,
    },
    addressText: {
      fontSize: FONT_SIZES.s,
      color: COLORS.textDim,
    },
    descriptionText: {
      fontSize: FONT_SIZES.m,
      color: COLORS.text,
      lineHeight: 22,
    },
    jobItemsList: {
      gap: SPACING.s,
    },
    jobItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    jobItemNumber: {
      fontSize: FONT_SIZES.s,
      fontWeight: '700',
      color: COLORS.primary,
      width: 20,
    },
    jobItemLabel: {
      fontSize: FONT_SIZES.m,
      color: COLORS.text,
      flex: 1,
    },
    jobItemPhotoIcon: {
      padding: 4,
    },
    viewMoreBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: SPACING.xs,
    },
    viewMoreText: {
      fontSize: FONT_SIZES.s,
      color: COLORS.primary,
      fontWeight: '600',
    },
    visibilityToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: SPACING.m,
      backgroundColor: COLORS.surfaceHighlight,
      borderRadius: RADIUS.m,
      marginTop: SPACING.l,
    },
    visibilityTogglePublic: {
      backgroundColor: COLORS.secondary + '10',
      borderColor: COLORS.secondary + '30',
      borderWidth: 1,
    },
    visibilityToggleLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.m,
      flex: 1,
    },
    visibilityToggleText: {
      fontSize: FONT_SIZES.m,
      fontWeight: '700',
      color: COLORS.text,
    },
    visibilityToggleTextPublic: {
      color: COLORS.secondary,
    },
    visibilityToggleHint: {
      fontSize: FONT_SIZES.xs,
      color: COLORS.textMuted,
    },
    editPhotosBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      padding: SPACING.m,
      marginTop: SPACING.m,
      borderWidth: 1,
      borderColor: COLORS.primary + '30',
      borderRadius: RADIUS.m,
    },
    editPhotosBtnText: {
      fontSize: FONT_SIZES.m,
      fontWeight: '600',
      color: COLORS.primary,
    },
    createEstimateBtn: {
      marginHorizontal: SPACING.m,
      height: 56,
      borderRadius: RADIUS.m,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      marginBottom: SPACING.xl,
    },
    createEstimateText: {
      fontSize: FONT_SIZES.l,
      fontWeight: '800',
      color: COLORS.white,
    },
    section: {
      marginBottom: SPACING.xl,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACING.m,
      marginBottom: SPACING.m,
    },
    sectionTitle: {
      fontSize: FONT_SIZES.l,
      fontWeight: '800',
      color: COLORS.text,
    },
    sectionBadge: {
      backgroundColor: COLORS.surfaceHighlight,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    sectionBadgeText: {
      fontSize: FONT_SIZES.xs,
      fontWeight: '700',
      color: COLORS.textMuted,
    },
    emptyContainer: {
      alignItems: 'center',
      padding: SPACING.xl,
      backgroundColor: COLORS.surface,
      marginHorizontal: SPACING.m,
      borderRadius: RADIUS.l,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderStyle: 'dashed',
    },
    emptyIconBg: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: COLORS.primary + '10',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: SPACING.m,
    },
    emptyTitle: {
      fontSize: FONT_SIZES.l,
      fontWeight: '700',
      color: COLORS.text,
      marginBottom: SPACING.xs,
    },
    emptySubtitle: {
      fontSize: FONT_SIZES.m,
      color: COLORS.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },
    profitCard: {
      marginHorizontal: SPACING.m,
      padding: SPACING.l,
      backgroundColor: COLORS.surface,
      borderRadius: RADIUS.l,
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    profitRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.s,
    },
    profitLabel: {
      fontSize: FONT_SIZES.m,
      color: COLORS.textMuted,
    },
    profitValue: {
      fontSize: FONT_SIZES.m,
      color: COLORS.text,
      fontWeight: '600',
    },
    profitDivider: {
      height: 1,
      backgroundColor: COLORS.border,
      marginVertical: SPACING.m,
    },
    profitLabelBold: {
      fontSize: FONT_SIZES.l,
      fontWeight: '800',
      color: COLORS.text,
    },
    profitValueBold: {
      fontSize: FONT_SIZES.xl,
      fontWeight: '900',
      color: COLORS.secondary,
    },
    profitTapHint: {
      alignItems: 'center',
      marginTop: SPACING.m,
    },
    profitTapHintText: {
      fontSize: FONT_SIZES.xs,
      color: COLORS.textDim,
    },
    gallerySection: {
      marginTop: SPACING.xl,
    },
    galleryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACING.m,
      marginBottom: SPACING.m,
    },
    addPhotosBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    addPhotosBtnText: {
      fontSize: FONT_SIZES.s,
      color: COLORS.primary,
      fontWeight: '600',
    },
    galleryGrid: {
      paddingHorizontal: SPACING.m,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    galleryItem: {
      width: (width - (SPACING.m * 2) - 16) / 3,
      aspectRatio: 1,
      borderRadius: RADIUS.m,
      overflow: 'hidden',
    },
    galleryImage: {
      width: '100%',
      height: '100%',
    },
    morePhotosOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    morePhotosText: {
      color: COLORS.white,
      fontSize: FONT_SIZES.l,
      fontWeight: '800',
    },
    lockedContainer: {
      alignItems: 'center',
      padding: SPACING.xl,
      backgroundColor: COLORS.backgroundHighlight,
      marginHorizontal: SPACING.m,
      borderRadius: RADIUS.l,
    },
    lockedIconBg: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: COLORS.surfaceHighlight,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: SPACING.m,
    },
    lockedTitle: {
      fontSize: FONT_SIZES.m,
      fontWeight: '700',
      color: COLORS.text,
      marginBottom: SPACING.xs,
    },
    lockedSubtitle: {
      fontSize: FONT_SIZES.s,
      color: COLORS.textMuted,
      textAlign: 'center',
    },
    finishProjectBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      marginTop: SPACING.xxl,
      marginHorizontal: SPACING.m,
      paddingVertical: SPACING.m,
      paddingHorizontal: SPACING.l,
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      borderRadius: RADIUS.m,
      borderWidth: 1,
      borderColor: 'rgba(239, 68, 68, 0.3)',
    },
    finishProjectText: {
      fontSize: FONT_SIZES.l,
      fontWeight: '800',
      color: COLORS.error,
    },
    finishHintText: {
      fontSize: FONT_SIZES.xs,
      color: COLORS.textDim,
      textAlign: 'center',
      marginTop: 4,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      justifyContent: 'flex-end',
    },
    photoSelectorModal: {
      backgroundColor: COLORS.surface,
      borderTopLeftRadius: RADIUS.xl,
      borderTopRightRadius: RADIUS.xl,
      height: '90%',
      padding: SPACING.l,
    },
    photoSelectorHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: SPACING.m,
    },
    photoSelectorTitle: {
      fontSize: FONT_SIZES.xl,
      fontWeight: '800',
      color: COLORS.text,
    },
    photoSelectorHint: {
      fontSize: FONT_SIZES.m,
      color: COLORS.textMuted,
      marginBottom: SPACING.l,
    },
    photoSelectorActions: {
      flexDirection: 'row',
      gap: SPACING.m,
      marginBottom: SPACING.l,
    },
    photoSelectorActionBtn: {
      paddingHorizontal: SPACING.m,
      paddingVertical: 8,
      borderRadius: RADIUS.m,
      backgroundColor: COLORS.surfaceHighlight,
    },
    photoSelectorActionText: {
      fontSize: FONT_SIZES.s,
      fontWeight: '600',
      color: COLORS.text,
    },
    photoSelectorGrid: {
      flex: 1,
    },
    photoSelectorItem: {
      width: (width - (SPACING.l * 2) - 16) / 3,
      aspectRatio: 1,
      borderRadius: RADIUS.m,
      overflow: 'hidden',
      borderWidth: 2,
      borderColor: 'transparent',
    },
    photoSelectorItemSelected: {
      borderColor: COLORS.primary,
    },
    photoSelectorImage: {
      width: '100%',
      height: '100%',
    },
    photoSelectorCheck: {
      position: 'absolute',
      top: 8,
      right: 8,
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: 'rgba(0,0,0,0.3)',
      borderWidth: 1.5,
      borderColor: COLORS.white,
      justifyContent: 'center',
      alignItems: 'center',
    },
    photoSelectorCheckSelected: {
      backgroundColor: COLORS.primary,
      borderColor: COLORS.primary,
    },
    photoSelectorFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: SPACING.l,
      borderTopWidth: 1,
      borderTopColor: COLORS.border,
    },
    photoSelectorCount: {
      fontSize: FONT_SIZES.m,
      fontWeight: '600',
      color: COLORS.text,
    },
    photoSelectorSaveBtn: {
      paddingHorizontal: SPACING.xl,
      height: 48,
      borderRadius: RADIUS.m,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    photoSelectorSaveBtnText: {
      color: COLORS.white,
      fontSize: FONT_SIZES.m,
      fontWeight: '700',
    },
    photoSelectorOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: SPACING.l,
    },
    photoSelectorContainer: {
      width: '100%',
      backgroundColor: COLORS.surface,
      borderRadius: RADIUS.l,
      padding: SPACING.l,
      maxHeight: '80%',
      ...GLASS?.card,
    },
    costsList: {
      gap: SPACING.s,
      marginBottom: SPACING.l,
    },
    costItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: SPACING.m,
      backgroundColor: COLORS.surfaceHighlight,
      borderRadius: RADIUS.m,
    },
    costName: {
      fontSize: FONT_SIZES.m,
      fontWeight: '600',
      color: COLORS.text,
    },
    costNotes: {
      fontSize: FONT_SIZES.xs,
      color: COLORS.textDim,
    },
    costAmount: {
      fontSize: FONT_SIZES.m,
      fontWeight: '700',
      color: COLORS.error,
    },
    costInput: {
      backgroundColor: COLORS.surfaceHighlight,
      borderRadius: RADIUS.m,
      padding: SPACING.m,
      color: COLORS.text,
      marginBottom: SPACING.m,
      fontSize: FONT_SIZES.m,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: COLORS.background,
    },
  });
};
